export const mockMonthData = {
  months: [
    {
      id: 100,
      name: "January",
      dateMonth: 1,
      monthPainelContabilTotalizer: {
        name: "TOTAL DO ATIVO",
        totalValue: 225057932.28,
      },
      totalizer: [
        {
          id: 1180,
          typeOrder: 1,
          name: "Ativo Financeiro",
          totalValue: 108963673.65,
          classifications: [],
        },
        {
          id: 1181,
          typeOrder: 2,
          name: "Caixa e Equivalente de Caixa",
          totalValue: 101311557.51,
          classifications: [
            {
              id: 361,
              typeOrder: 1,
              name: "Caixas",
              value: 96276531.69,
              datas: Array(3).fill({
                id: 35788,
                typeOrder: 0,
                name: "A T I V O",
                costCenter: "1",
                initialValue: 0,
                creditValue: 0,
                debitValue: 0,
                value: 32092177.23,
              }),
            },
            {
              id: 362,
              typeOrder: 2,
              name: "Bancos",
              value: 5035025.82,
              datas: Array(3).fill({
                id: 35793,
                typeOrder: 0,
                name: "BANCOS CONTA MOVIMENTO",
                costCenter: "1.1.1.002",
                initialValue: 0,
                creditValue: 0,
                debitValue: 0,
                value: 1678341.94,
              }),
            },
          ],
        },
        {
          id: 1182,
          typeOrder: 3,
          name: "Aplicação Financeira",
          totalValue: 7652116.14,
          classifications: [
            {
              id: 363,
              typeOrder: 3,
              name: "Aplicações Financeiras",
              value: 7652116.14,
              datas: Array(3).fill({
                id: 35798,
                typeOrder: 0,
                name: "APLICACOES FINANCEIRAS",
                costCenter: "1.1.1.003",
                initialValue: 0,
                creditValue: 0,
                debitValue: 0,
                value: 2550705.38,
              }),
            },
          ],
        },
        {
          id: 1183,
          typeOrder: 4,
          name: "Ativo Operacional",
          totalValue: 1628099.16,
          classifications: [],
        },
        {
          id: 1184,
          typeOrder: 5,
          name: "Clientes",
          totalValue: 1628099.16,
          classifications: [
            {
              id: 364,
              typeOrder: 4,
              name: "Clientes",
              value: 1628099.16,
              datas: [
                {
                  id: 35808,
                  typeOrder: 0,
                  name: "DUPLICATAS PECAS/ACESSORIOS E SERVICOS",
                  costCenter: "1.1.2.001.000003",
                  initialValue: 0,
                  creditValue: 0,
                  debitValue: 0,
                  value: 542699.72,
                },
                {
                  id: 35807,
                  typeOrder: 0,
                  name: "DUPLICATAS SEMI NOVOS",
                  costCenter: "1.1.2.001.000002",
                  initialValue: 0,
                  creditValue: 0,
                  debitValue: 0,
                  value: 0.0,
                },
                {
                  id: 35808,
                  typeOrder: 0,
                  name: "DUPLICATAS PECAS/ACESSORIOS E SERVICOS",
                  costCenter: "1.1.2.001.000003",
                  initialValue: 0,
                  creditValue: 0,
                  debitValue: 0,
                  value: 542699.72,
                },
                {
                  id: 35807,
                  typeOrder: 0,
                  name: "DUPLICATAS SEMI NOVOS",
                  costCenter: "1.1.2.001.000002",
                  initialValue: 0,
                  creditValue: 0,
                  debitValue: 0,
                  value: 0.0,
                },
                {
                  id: 35808,
                  typeOrder: 0,
                  name: "DUPLICATAS PECAS/ACESSORIOS E SERVICOS",
                  costCenter: "1.1.2.001.000003",
                  initialValue: 0,
                  creditValue: 0,
                  debitValue: 0,
                  value: 542699.72,
                },
                {
                  id: 35807,
                  typeOrder: 0,
                  name: "DUPLICATAS SEMI NOVOS",
                  costCenter: "1.1.2.001.000002",
                  initialValue: 0,
                  creditValue: 0,
                  debitValue: 0,
                  value: 0.0,
                },
              ],
            },
          ],
        },
        {
          id: 1185,
          typeOrder: 6,
          name: "Estoques",
          totalValue: 0,
          classifications: [
            {
              id: 369,
              typeOrder: 9,
              name: "Estoques",
              value: 0,
              datas: [],
            },
          ],
        },
        {
          id: 1186,
          typeOrder: 7,
          name: "Outros Ativos Operacionais",
          totalValue: 0,
          classifications: [
            {
              id: 365,
              typeOrder: 5,
              name: "Outros Créditos",
              value: 0,
              datas: [],
            },
            {
              id: 366,
              typeOrder: 6,
              name: "Adiantamentos",
              value: 0,
              datas: [],
            },
            {
              id: 367,
              typeOrder: 7,
              name: "Impostos a Recuperar / Antecipações",
              value: 0,
              datas: [],
            },
            { id: 368, typeOrder: 8, name: "Empréstimos", value: 0, datas: [] },
            {
              id: 370,
              typeOrder: 10,
              name: "Despesas a Apropriar",
              value: 0,
              datas: [],
            },
          ],
        },
        {
          id: 1187,
          typeOrder: 8,
          name: "Outros Ativos Operacionais Total",
          totalValue: 0,
          classifications: [],
        },
        {
          id: 1188,
          typeOrder: 9,
          name: "Contas Transitórias",
          totalValue: 0,
          classifications: [],
        },
        {
          id: 1189,
          typeOrder: 10,
          name: "Ativo Não Circulante",
          totalValue: 1937193.33,
          classifications: [],
        },
        {
          id: 1190,
          typeOrder: 11,
          name: "Ativo Não Circulante Financeiro",
          totalValue: 0,
          classifications: [],
        },
        {
          id: 1191,
          typeOrder: 12,
          name: "Ativo Não Circulante Operacional",
          totalValue: 1937193.33,
          classifications: [
            {
              id: 371,
              typeOrder: 11,
              name: "Consórcio",
              value: 1886.58,
              datas: Array(3).fill({
                id: 35822,
                typeOrder: 0,
                name: "CARTAO VISA ELECTRON REDE",
                costCenter: "1.1.2.001.000118",
                initialValue: 0,
                creditValue: 0,
                debitValue: 0,
                value: 628.86,
              }),
            },
            {
              id: 372,
              typeOrder: 12,
              name: "Empréstimos a Coligadas e Controlada",
              value: 1935306.75,
              datas: Array(3).fill({
                id: 35827,
                typeOrder: 0,
                name: "CARTAO VISA REDE",
                costCenter: "1.1.2.001.000128",
                initialValue: 0,
                creditValue: 0,
                debitValue: 0,
                value: 645102.25,
              }),
            },
            {
              id: 373,
              typeOrder: 13,
              name: "Depósitos Judiciais",
              value: 0,
              datas: [],
            },
            {
              id: 374,
              typeOrder: 14,
              name: "Outros Créditos LP",
              value: 0,
              datas: [],
            },
          ],
        },
        {
          id: 1192,
          typeOrder: 13,
          name: "Ativo Fixo",
          totalValue: 0,
          classifications: [],
        },
        {
          id: 1193,
          typeOrder: 14,
          name: "Investimentos",
          totalValue: 0,
          classifications: [
            {
              id: 376,
              typeOrder: 16,
              name: "Investimentos",
              value: 0,
              datas: [],
            },
          ],
        },
        {
          id: 1194,
          typeOrder: 15,
          name: "Imobilizado",
          totalValue: 0,
          classifications: [
            {
              id: 377,
              typeOrder: 17,
              name: "Imobilizado",
              value: 0,
              datas: [],
            },
          ],
        },
        {
          id: 1195,
          typeOrder: 16,
          name: "Depreciação / Amort. Acumulada",
          totalValue: 0,
          classifications: [
            {
              id: 379,
              typeOrder: 19,
              name: "Depreciação / Amortização Acumuladas",
              value: 0,
              datas: [],
            },
          ],
        },
        {
          id: 1196,
          typeOrder: 17,
          name: "Intangível",
          totalValue: 0,
          classifications: [
            {
              id: 378,
              typeOrder: 18,
              name: "Intangível",
              value: 0,
              datas: [],
            },
          ],
        },
      ],
    },
  ],
};
